export const defaultThemeColors = {
	light: {
		headerBg: '#fff',
		sidemenuBg: '#fff',
		sidemenuBgHover: '#f6f6f6',
		sidemenuBgActive: '#e5effa',
		sidemenuColorActive: '#1976d2',
		menuBg: '#fff',
		menuBgHover: '#f6f6f6',
		messagesBg: '#f8f9fa',
		textColorDark: '#0a0a0a',
		textColor: '#0a0a0a',
		inputBg: '#fff',
		spinnerColor: '#333',
		iconsColor: {
			search: '#9ca6af',
			add: '#1976d2',
			menu: '#0a0a0a',
			close: '#9ca6af',
			closeImage: '#fff',
			file: '#1976d2',
			paperclip: '#1976d2',
			closeOutline: '#1976d2',
			send: '#1976d2',
			sendDisabled: '#9ca6af',
			emoji: '#1976d2',
			document: '#1976d2',
			pencil: '#1976d2',
			pencilEdited: '#9e9e9e',
			trash: '#f44336',
			checkmark: '#0696c7'
		}
	},
	dark: {
		headerBg: '#26272e',
		sidemenuBg: '#26272e',
		sidemenuBgHover: '#202024',
		sidemenuBgActive: '#1C1D21',
		sidemenuColorActive: '#fff',
		menuBg: '#26272e',
		menuBgHover: '#1C1D21',
		messagesBg: '#1C1D21',
		textColorDark: '#0a0a0a',
		textColor: '#fff',
		inputBg: '#34343b',
		spinnerColor: '#fff',
		iconsColor: {
			search: '#9ca6af',
			add: '#fff',
			menu: '#fff',
			close: '#9ca6af',
			closeImage: '#fff',
			file: '#fff',
			paperclip: '#fff',
			closeOutline: '#fff',
			send: '#fff',
			sendDisabled: '#9ca6af',
			emoji: '#fff',
			document: '#1976d2',
			pencil: '#1976d2',
			pencilEdited: '#9e9e9e',
			trash: '#f44336',
			checkmark: '#0696c7'
		}
	}
}

export const cssThemeVars = ({
	headerBg,
	sidemenuBg,
	sidemenuBgHover,
	sidemenuBgActive,
	sidemenuColorActive,
	menuBg,
	menuBgHover,
	messagesBg,
	textColorDark,
	textColor,
	inputBg,
	spinnerColor,
	iconsColor
}) => {
	return {
		'--chat-header-bg-color': headerBg,
		'--chat-bg-color': sidemenuBg,
		'--chat-bg-color-hover': sidemenuBgHover,
		'--chat-bg-color-active': sidemenuBgActive,
		'--chat-bg-color-content': messagesBg,
		'--chat-color-dark': textColorDark,
		'--chat-color': textColor,
		'--chat-color-active': sidemenuColorActive,
		'--chat-bg-menu': menuBg,
		'--chat-bg-menu-hover': menuBgHover,
		'--chat-color-input': inputBg,
		'--chat-color-spinner': spinnerColor,
		'--chat-icon-color-search': iconsColor.search,
		'--chat-icon-color-add': iconsColor.add,
		'--chat-icon-color-menu': iconsColor.menu,
		'--chat-icon-color-close': iconsColor.close,
		'--chat-icon-color-close-image': iconsColor.closeImage,
		'--chat-icon-color-file': iconsColor.file,
		'--chat-icon-color-paperclip': iconsColor.paperclip,
		'--chat-icon-color-close-outline': iconsColor.closeOutline,
		'--chat-icon-color-send': iconsColor.send,
		'--chat-icon-color-send-disabled': iconsColor.sendDisabled,
		'--chat-icon-color-emoji': iconsColor.emoji,
		'--chat-icon-color-document': iconsColor.document,
		'--chat-icon-color-pencil': iconsColor.pencil,
		'--chat-edited-icon-color-pencil': iconsColor.pencilEdited,
		'--chat-icon-color-trash': iconsColor.trash,
		'--chat-icon-color-checkmark': iconsColor.checkmark
	}
}
