export const IMAGE_TYPES = ['png', 'jpg', 'jpeg', 'webp', 'svg', 'gif']
export const VIDEO_TYPES = ['mp4', 'video/ogg', 'webm', 'quicktime']
export const AUDIO_TYPES = ['mp3', 'audio/ogg', 'wav', 'mpeg']
export const TEXT_TYPES = [ 'text', 'text/plain', 'text/csv' ]
export const PDF_TYPES = ['pdf', 'application/pdf']
export const SVG_TYPES = ['svg', 'image/svg+xml']
